name: Yarn Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    

jobs:
  yarn_build_prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: yarn
    - run: yarn build-prod
